services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: item_storage
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  api:
    build: ./backend/api
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend

  bookings:
    build: ./backend/bookings
    container_name: bookings-service
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: item_storage
      DB_PORT: 5432
    ports:
      - "4000:4000"
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge
